// Generated by build.sh from cpp/02_adders/adder_delay_compare.cpp - do not edit by hand.
window.TRACES = window.TRACES || {};
window.TRACES["adder_delay_compare"] = {
  id: "adder_delay_compare",
  name: "Ripple vs Carry-Look-Ahead",
  chapter: "Adders",
  complexity: { time: "O(n)", space: "O(1)" },
  view: "table",
  panels: [],
  displaySource: [
    "// Ripple vs Carry-Look-Ahead — Why the Circuit's Shape Matters",
    "//",
    "// An n-bit ripple-carry has to wait for n cascaded carries: the delay grows",
    "// linearly with the width. A carry-look-ahead computes every carry directly",
    "// from the inputs with a fixed level of gates: the delay stays constant.",
    "// Same result, different circuit shape.",
    "#include <string>",
    "",
    "",
    "int main() {",
    "",
    "    const int NMAX = 8;",
    "    for (int n = 1; n <= NMAX; n++) {",
    "        int ripple = 2 * n;",
    "        int cla = 4;",
    "    }",
    "",
    "}"
  ],
  lineMap: {"1":0,"2":1,"3":2,"4":3,"5":4,"6":5,"7":6,"8":6,"9":7,"10":7,"11":8,"12":9,"13":9,"14":9,"15":10,"16":11,"17":12,"18":13,"19":14,"20":14,"21":14,"22":14,"23":14,"24":14,"25":14,"26":14,"27":14,"28":14,"29":15,"30":16,"31":16,"32":17},
  inputs: [
    {"label":"Delay as width grows","steps":[{"line":20,"function":"main","vars":{"n":1,"ripple delay":2,"CLA delay":4},"note":"At 1 bits: ripple-carry takes 2 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4}}},
      {"line":20,"function":"main","vars":{"n":2,"ripple delay":4,"CLA delay":4},"note":"At 2 bits: ripple-carry takes 4 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4},"n=2":{"ripple":4,"CLA":4}}},
      {"line":20,"function":"main","vars":{"n":3,"ripple delay":6,"CLA delay":4},"note":"At 3 bits: ripple-carry takes 6 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4},"n=2":{"ripple":4,"CLA":4},"n=3":{"ripple":6,"CLA":4}}},
      {"line":20,"function":"main","vars":{"n":4,"ripple delay":8,"CLA delay":4},"note":"At 4 bits: ripple-carry takes 8 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4},"n=2":{"ripple":4,"CLA":4},"n=3":{"ripple":6,"CLA":4},"n=4":{"ripple":8,"CLA":4}}},
      {"line":20,"function":"main","vars":{"n":5,"ripple delay":10,"CLA delay":4},"note":"At 5 bits: ripple-carry takes 10 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4},"n=2":{"ripple":4,"CLA":4},"n=3":{"ripple":6,"CLA":4},"n=4":{"ripple":8,"CLA":4},"n=5":{"ripple":10,"CLA":4}}},
      {"line":20,"function":"main","vars":{"n":6,"ripple delay":12,"CLA delay":4},"note":"At 6 bits: ripple-carry takes 12 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4},"n=2":{"ripple":4,"CLA":4},"n=3":{"ripple":6,"CLA":4},"n=4":{"ripple":8,"CLA":4},"n=5":{"ripple":10,"CLA":4},"n=6":{"ripple":12,"CLA":4}}},
      {"line":20,"function":"main","vars":{"n":7,"ripple delay":14,"CLA delay":4},"note":"At 7 bits: ripple-carry takes 14 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4},"n=2":{"ripple":4,"CLA":4},"n=3":{"ripple":6,"CLA":4},"n=4":{"ripple":8,"CLA":4},"n=5":{"ripple":10,"CLA":4},"n=6":{"ripple":12,"CLA":4},"n=7":{"ripple":14,"CLA":4}}},
      {"line":20,"function":"main","vars":{"n":8,"ripple delay":16,"CLA delay":4},"note":"At 8 bits: ripple-carry takes 16 cascaded gate delays, carry-look-ahead takes 4 regardless of n.","tables":{"n=1":{"ripple":2,"CLA":4},"n=2":{"ripple":4,"CLA":4},"n=3":{"ripple":6,"CLA":4},"n=4":{"ripple":8,"CLA":4},"n=5":{"ripple":10,"CLA":4},"n=6":{"ripple":12,"CLA":4},"n=7":{"ripple":14,"CLA":4},"n=8":{"ripple":16,"CLA":4}}}]}
  ]
};
